# -*- coding: utf-8 -*-
"""MA705-wordcloud

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TScrZ-ncmnWPUnkst9CeuKGCNEOinGsK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import re
import collections
!pip install wordcloud
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

bigfootDF = pd.read_csv('bigfoot.csv', index_col=False)

bigfootDF = bigfootDF.dropna(subset=['observed'])
stop_words = set(stopwords.words('english'))
pat = '|'.join(r"\b{}\b".format(x) for x in stop_words)
bigfootDF['observed'] = bigfootDF['observed'].str.lower()
bigfootDF['observed'] = bigfootDF['observed'].str.replace(pat, "")
bigfoot_Text = bigfootDF.observed
text = "".join(str(review) for review in bigfoot_Text)

word_list = []

search_word = ['\d+ feet tall', '\d+ pound[s]', '\w+ hair', '\w+ appearance', '\w+ skin', '\w+ eyes', '\w+ \w+ nose', '\w+ hand', '\w+ leg']
for item in search_word:
  search = re.findall(item, text)
  word_list += search

from collections import Counter

word_cloud_lst = Counter(word_list)
wordcloud = WordCloud(max_font_size=50, max_words=200, background_color="white", width=600, height=400).generate_from_frequencies(word_cloud_lst)
plt.figure(figsize=(20,10))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.show()